const { chromium } = require('../web/node_modules/playwright');
const assert = require('node:assert/strict');
const base = process.env.QA_BASE_URL;
if (!base) throw new Error('Set QA_BASE_URL to the deployed site, including its repository path.');
(async () => {
  const browser = await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE} : {});
  try {
    const page = await browser.newPage({ reducedMotion: 'reduce' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    assert.equal((await page.goto(base)).status(), 200);
    await page.getByRole('button', { name: 'Help & guide' }).click();
    const download = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Download guide' }).click();
    assert.equal((await download).suggestedFilename(), 'The-Black-Wall-Guide.md');
    await page.getByRole('button', { name: 'Close help' }).click();
    await page.getByLabel('Passphrase', { exact: true }).fill('deployment test passphrase');
    await page.getByLabel('Repeat passphrase').fill('deployment test passphrase');
    await page.getByRole('button', { name: 'Create private archive' }).click();
    await page.getByRole('link', { name: 'Create a new room' }).click();
    await page.getByLabel('Room name').fill('Deployment check');
    await page.getByRole('button', { name: 'Hang it up' }).click();
    await page.getByRole('button', { name: 'Pin a thought', exact: true }).click();
    await page.getByLabel('Your thought').fill('Synthetic deployment check; browser-local only.');
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByText('Saved encrypted on this device', { exact: true }).waitFor();
    const roomURL = page.url();
    const wood = await page.locator('.diary-wall').evaluate(el => getComputedStyle(el).backgroundImage.match(/url\("?([^"\)]+)/)?.[1]);
    assert.ok(wood);
    assert.equal((await page.request.get(wood)).status(), 200);
    await page.reload();
    await page.getByLabel('Passphrase', { exact: true }).fill('deployment test passphrase');
    await page.getByRole('button', { name: 'Unlock archive' }).click();
    assert.equal(page.url(), roomURL);
    await page.getByRole('button', { name: 'Share room', exact: true }).click();
    const share = page.getByRole('dialog', { name: 'Share privately' });
    await share.getByLabel('Share passphrase', { exact: true }).fill('deployment share passphrase');
    await share.getByLabel('Repeat passphrase').fill('deployment share passphrase');
    await share.getByRole('button', { name: 'Prepare private share' }).click();
    const url = await share.getByLabel('Protected share link').inputValue();
    assert.ok(url.startsWith(`${base.replace(/\/$/, '')}/shared/#`));
    const recipient = await browser.newPage({ reducedMotion: 'reduce' });
    assert.equal((await recipient.goto(url)).status(), 200);
    await recipient.getByLabel('Share passphrase', { exact: true }).fill('deployment share passphrase');
    await recipient.getByRole('button', { name: 'Open', exact: true }).click();
    await recipient.getByRole('button', { name: /Open your letter/ }).click();
    await recipient.locator('.shared-paper--main .rich-content').waitFor();
    assert.ok((await recipient.locator('.shared-paper--main .rich-content').textContent()).includes('Synthetic deployment check; browser-local only.'));
    await recipient.getByRole('button', { name: 'Hide screen' }).click();
    await recipient.getByRole('button', { name: 'Return', exact: true }).waitFor();
    assert.deepEqual(errors, []);
    console.log('PASS: hosted entry, help download, room creation, encrypted save/reload, wood asset, protected share URL and recipient unlock.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
