const {chromium}=require('../web/node_modules/playwright');const assert=require('node:assert/strict');
const base=process.env.QA_BASE_URL||'http://127.0.0.1:5173';const PASS='large media archive phrase';
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(base);await page.getByLabel('Passphrase',{exact:true}).fill(PASS);await page.getByLabel('Repeat passphrase').fill(PASS);await page.getByRole('button',{name:'Create private archive'}).click();await page.getByLabel('What is on your mind?').fill('Large media test');await page.getByRole('button',{name:'Keep it',exact:true}).click();await page.getByRole('button',{name:'Keep this thought'}).click();await page.locator('.note-open').click();
async function attach(kind){return page.evaluate(async kind=>{let file;
if(kind==='audio'){const length=180*8000*2;const bytes=new Uint8Array(44+length),view=new DataView(bytes.buffer);function text(at,s){[...s].forEach((c,i)=>bytes[at+i]=c.charCodeAt(0))}text(0,'RIFF');view.setUint32(4,bytes.length-8,true);text(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,16000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,length,true);file=new File([bytes],'three-minutes.wav',{type:'audio/wav'});}
if(kind==='photo'){const c=document.createElement('canvas');c.width=2048;c.height=2048;const ctx=c.getContext('2d');const pixels=ctx.createImageData(c.width,c.height);let seed=123;for(let i=0;i<pixels.data.length;i+=4){seed=(Math.imul(seed,1664525)+1013904223)|0;pixels.data[i]=seed&255;pixels.data[i+1]=seed>>>8&255;pixels.data[i+2]=seed>>>16&255;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const blob=await new Promise(r=>c.toBlob(r,'image/png'));file=new File([blob],'large-photo.png',{type:'image/png'});}
if(kind==='video'){const c=document.createElement('canvas');c.width=128;c.height=128;const stream=c.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const parts=[];const result=new Promise(resolve=>{recorder.ondataavailable=e=>parts.push(e.data);recorder.onstop=()=>resolve(new Blob([...parts,new Uint8Array(4*1024*1024)],{type:'video/webm'}));});recorder.start();c.getContext('2d').fillRect(0,0,128,128);await new Promise(r=>setTimeout(r,350));recorder.stop();const blob=await result;stream.getTracks().forEach(t=>t.stop());file=new File([blob],'large-video.webm',{type:'video/webm'});}
const transfer=new DataTransfer();transfer.items.add(file);const input=document.querySelector('.attachment-button input');input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));return file.size;},kind);}
const audio=await attach('audio');await page.locator('.attachments audio').waitFor();assert.ok(audio>1024*1024);assert.ok(await page.locator('.attachments audio').evaluate(e=>e.duration)>120);
const photo=await attach('photo');await page.locator('.attachments img').waitFor();assert.ok(photo>3*1024*1024);const video=await attach('video');await page.locator('.attachments video').waitFor();assert.ok(video>3*1024*1024);assert.ok(audio+photo+video>8*1024*1024);
await page.getByText('Saved encrypted on this device',{exact:true}).waitFor();const download=page.waitForEvent('download');await page.locator('.note-editor').getByRole('button',{name:'Export encrypted backup',exact:true}).click();const backup=await download;const path='/tmp/large-media-backup.json';await backup.saveAs(path);assert.ok(require('node:fs').statSync(path).size>20000000);
const restored=await browser.newPage();await restored.goto(base);await restored.locator('input[type=file]').setInputFiles(path);await restored.getByLabel('Passphrase',{exact:true}).fill(PASS);await restored.getByRole('button',{name:'Restore backup',exact:true}).click();await restored.getByRole('link',{name:'Open My thoughts',exact:true}).click();await restored.locator('.note-open').click();await restored.locator('.attachments img').waitFor();assert.equal(await restored.locator('.attachments figure').count(),3);assert.ok(await restored.locator('.attachments audio').evaluate(e=>e.duration)>120);
await restored.getByRole('button',{name:'Share note',exact:true}).click();let dialog=restored.getByRole('dialog',{name:'Share privately',exact:true});await dialog.getByLabel('Share passphrase',{exact:true}).fill(PASS);await dialog.getByLabel('Repeat passphrase',{exact:true}).fill(PASS);await dialog.getByRole('button',{name:'Prepare private share'}).click();await dialog.getByRole('button',{name:'Download shared file'}).waitFor();assert.equal(await dialog.getByLabel('Protected share link').count(),0);const sharedDownload=restored.waitForEvent('download');await dialog.getByRole('button',{name:'Download shared file'}).click();const shared=await sharedDownload;await shared.saveAs('/tmp/large-media-share.json');await dialog.getByRole('button',{name:'Done',exact:true}).click();
const recipient=await browser.newPage();await recipient.goto(base+'/shared');await recipient.getByLabel('Open shared file').setInputFiles('/tmp/large-media-share.json');await recipient.getByLabel('Share passphrase',{exact:true}).fill(PASS);await recipient.getByRole('button',{name:'Open shared snapshot'}).click();await recipient.locator('.shared-notes img').waitFor();assert.equal(await recipient.locator('.shared-notes figure').count(),3);await recipient.close();
await restored.getByRole('button',{name:'Lock note',exact:true}).click();dialog=restored.getByRole('dialog',{name:'Lock item',exact:true});await dialog.getByLabel('New item passphrase',{exact:true}).fill(PASS);await dialog.getByLabel('Repeat passphrase',{exact:true}).fill(PASS);await dialog.getByRole('button',{name:'Lock item',exact:true}).click();await restored.locator('.note-editor').waitFor({state:'detached'});await restored.locator('.locked-note').getByRole('button',{name:'Unlock note',exact:true}).click();dialog=restored.getByRole('dialog',{name:'Unlock item',exact:true});await dialog.getByLabel('Item passphrase',{exact:true}).fill(PASS);await dialog.getByLabel('Remove this lock so I can edit').check();await dialog.getByRole('button',{name:'Remove lock',exact:true}).click();await restored.locator('.note-open').click();await restored.locator('.attachments img').waitFor();assert.equal(await restored.locator('.attachments figure').count(),3);
console.log(`PASS: 3-minute audio (${audio} bytes), large photo (${photo} bytes), large video (${video} bytes), archive above 8 MB, backup above 20 MB, encrypted restore, protected-file share and lock/unlock of all three.`);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
