const { chromium } = require('../web/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const PASS = 'quiet sea private archive 2026';
const base = process.env.QA_BASE_URL || 'http://127.0.0.1:5173';
async function setup(page) { await page.goto(base); await page.getByLabel('Passphrase',{exact:true}).fill(PASS); await page.getByLabel('Repeat passphrase').fill(PASS); await page.getByRole('button',{name:'Create private archive'}).click(); await page.getByLabel('What is on your mind?').waitFor(); }
async function saved(page){await page.getByText('Saved encrypted on this device',{exact:true}).waitFor();}
function wav(){const data=Buffer.alloc(44+16000);data.write('RIFF');data.writeUInt32LE(data.length-8,4);data.write('WAVEfmt ',8);data.writeUInt32LE(16,16);data.writeUInt16LE(1,20);data.writeUInt16LE(1,22);data.writeUInt32LE(8000,24);data.writeUInt32LE(16000,28);data.writeUInt16LE(2,32);data.writeUInt16LE(16,34);data.write('data',36);data.writeUInt32LE(16000,40);return data;}
(async()=>{
 const browser=await chromium.launch();const dir=fs.mkdtempSync('/tmp/private-wall-qa-');
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await setup(page);
  assert.equal(await page.getByRole('button',{name:'Chimes off'}).getAttribute('aria-pressed'),'false');
  await page.getByLabel('What is on your mind?').fill('A secret thought about tomorrow.');
  await page.getByRole('button',{name:'Keep it',exact:true}).click();await page.getByLabel('Room name',{exact:true}).fill('Quiet diary');await page.getByRole('button',{name:'Keep this thought'}).click();
  assert.ok(!page.url().includes('quiet-diary'));await page.getByRole('button',{name:'Turn room light off'}).waitFor();
  await page.locator('.note-open').first().click();const writing=page.getByLabel('Your thought');
  assert.equal(await page.locator('.note-editor').evaluate(e=>e.matches(':modal')),true);
  for(let i=0;i<20;i++){await page.keyboard.press('Tab');assert.equal(await page.locator('.note-editor').evaluate(e=>document.activeElement===document.body||e.contains(document.activeElement)),true);}
  const text='**A secret thought**\n*This is gentle.*\n[unsafe](javascript:alert(1))\n<img src=x onerror=alert(1)>\nhttps://example.com\n'+'A long diary line with room to read. '.repeat(35);
  await writing.fill(text);await saved(page);
  assert.equal(await page.locator('.note-preview strong').textContent(),'A secret thought');assert.equal(await page.locator('.note-preview img, .note-preview script, .note-preview a[href^="javascript:"]').count(),0);
  page.once('dialog',d=>d.dismiss());await page.locator('.note-preview a').first().click();assert.equal(page.context().pages().length,1);
  await page.locator('.attachment-button input').setInputFiles({name:'quiet.wav',mimeType:'audio/wav',buffer:wav()});await page.locator('.attachments audio').waitFor();await saved(page);
  await page.locator('.attachment-button input').setInputFiles({name:'invalid.wav',mimeType:'audio/wav',buffer:Buffer.alloc(2*1024*1024)});await page.getByRole('alert').filter({hasText:'cannot be played'}).waitFor();
  await page.getByRole('button',{name:'Close note',exact:true}).click();await page.getByRole('button',{name:'Pin a thought',exact:true}).click();await writing.fill('I feel grateful today.');await page.getByRole('button',{name:'Previous note'}).click();await page.waitForFunction(expected=>document.querySelector('#note-writing')?.value===expected,text);assert.equal(await page.locator('.note-editor[open]').count(),1);assert.equal(await writing.inputValue(),text);await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('button',{name:'Turn room light off'}).click();await page.mouse.move(1,1);await page.waitForTimeout(950);
  assert.equal(await page.locator('.diary-note[data-revealed="true"]').count(),0);
  const card=page.locator('.diary-note').first();const box=await card.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(100);assert.equal(await card.getAttribute('data-revealed'),'true');assert.equal(await page.locator('.diary-note[data-revealed="true"]').count(),1);
  await page.screenshot({path:dir+'/room-dark.png'});
  await page.getByRole('button',{name:'Turn room light on'}).click();await saved(page);
  for(let i=0;i<3;i++){await page.getByRole('button',{name:'Turn room light off'}).click();await page.getByRole('button',{name:'Turn room light on'}).click();}await page.waitForTimeout(1100);assert.equal(await page.locator('.diary-note[data-revealed="true"]').count(),2);await page.screenshot({path:dir+'/room-light.png'});await page.getByRole('button',{name:'Chimes off'}).click();
  const snapshot=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('black-wall-private',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise(resolve=>{const r=db.transaction('vault').objectStore('vault').get('world');r.onsuccess=()=>resolve({vault:r.result,local:{...localStorage}})});});
  assert.equal(snapshot.vault.version,2);assert.ok(!JSON.stringify(snapshot).includes('secret thought'));assert.ok(!JSON.stringify(snapshot).includes('Quiet diary'));assert.ok(!('black-wall:v1' in snapshot.local));
  const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export encrypted backup'}).click();const download=await downloading;const backupPath=dir+'/backup.json';await download.saveAs(backupPath);
  await page.reload();await page.getByLabel('Passphrase',{exact:true}).fill('wrong password');await page.getByRole('button',{name:'Unlock archive'}).click();await page.getByRole('alert').filter({hasText:'incorrect'}).waitFor();await page.getByLabel('Passphrase',{exact:true}).fill(PASS);await page.getByRole('button',{name:'Unlock archive'}).click();await page.locator('.diary-note').first().waitFor();assert.equal(await page.locator('.diary-note').count(),2);assert.equal(await page.getByRole('button',{name:'Chimes on'}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Chimes on'}).click();
  await page.locator('.note-open').first().click();assert.equal(await writing.inputValue(),text);assert.equal(await page.locator('.attachments audio').count(),1);await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.locator('.release-note').last().click();await page.getByRole('button',{name:'Keep it',exact:true}).click();assert.equal(await page.locator('.diary-note').count(),2);
  await page.locator('.release-note').last().click();await page.getByRole('button',{name:'Let it go',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.diary-note').length===1);assert.equal(await page.locator('.diary-note').count(),1);await saved(page);
  await page.getByRole('link',{name:'← Lobby'}).click();for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});assert.equal(await page.locator('.lobby').evaluate(e=>e.scrollWidth>e.clientWidth),false,`lobby overflow ${width}`);await page.screenshot({path:dir+`/lobby-${width}.png`});}
  await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('link',{name:'Open Quiet diary'}).click();await page.locator('.note-open').first().focus();await page.keyboard.press('Enter');assert.equal(await writing.inputValue(),text);await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.keyboard.down('Escape');await page.waitForTimeout(600);await page.keyboard.up('Escape');await page.locator('.blank-page').waitFor();assert.equal(await page.locator('.diary-note,.note-editor').count(),0);await page.getByRole('button',{name:'Return',exact:true}).click();await page.getByRole('button',{name:'Unlock archive'}).waitFor();
  const restore=await browser.newPage();await restore.goto(base);await restore.locator('input[type=file]').setInputFiles(backupPath);await restore.getByLabel('Passphrase',{exact:true}).fill(PASS);await restore.getByRole('button',{name:'Restore backup'}).click();await restore.getByRole('link',{name:'Open Quiet diary'}).click();await restore.locator('.diary-note').first().waitFor();assert.equal(await restore.locator('.diary-note').count(),2);
  const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mobile=await mobileContext.newPage();await setup(mobile);await mobile.getByLabel('What is on your mind?').fill('Mobile thought');await mobile.getByRole('button',{name:'Keep it',exact:true}).tap();await mobile.getByRole('button',{name:'Keep this thought'}).tap();await mobile.locator('.note-open').tap();await mobile.getByLabel('Your thought').fill('Written on touch');assert.equal(await mobile.locator('.match-cursor').evaluate(e=>getComputedStyle(e).display),'none');await mobile.waitForTimeout(400);assert.equal(await mobile.locator('.note-editor').evaluate(e=>{const r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+30))&&e.scrollWidth<=e.clientWidth}),true);await mobile.screenshot({path:dir+'/mobile-editor.png'});await mobile.getByRole('button',{name:'Done',exact:true}).tap();await mobile.locator('.note-editor').waitFor({state:'detached'});await mobile.setViewportSize({width:320,height:844});await mobile.locator('.note-open').tap();await mobile.waitForTimeout(400);assert.equal(await mobile.locator('.note-editor').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await mobile.locator('.note-editor').getByRole('button',{name:'Hide screen'}).tap();await mobile.locator('.blank-page').waitFor();await mobileContext.close();
  await restore.getByRole('link',{name:'← Lobby'}).click();await restore.getByRole('button',{name:'Let Quiet diary go',exact:true}).click();await restore.locator('.release-dialog').getByRole('button',{name:'Keep it',exact:true}).click();assert.equal(await restore.getByRole('link',{name:'Open Quiet diary'}).count(),1);await restore.getByRole('button',{name:'Let Quiet diary go',exact:true}).click();await restore.locator('.release-dialog').getByRole('button',{name:'Let it go',exact:true}).click();await restore.getByText('Nothing here yet. Light one.').waitFor();await saved(restore);await restore.reload();await restore.getByLabel('Passphrase',{exact:true}).fill(PASS);await restore.getByRole('button',{name:'Unlock archive'}).click();await restore.getByText('Nothing here yet. Light one.').waitFor();
  assert.deepEqual(errors,[]);console.log('PASS: encryption, unlock/wrong password, rich text safety, invalid media rejection, radial reveal, one editor, release, backup/restore, panic hide, responsive and touch/reduced motion. '+dir);
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
