const { chromium } = require('../web/node_modules/playwright');
const assert = require('node:assert/strict');
const base = process.env.QA_BASE_URL || 'http://127.0.0.1:5173';
const pass = 'room motion testing phrase';
(async () => {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(base);
    await page.getByLabel('Passphrase', { exact: true }).fill(pass);
    await page.getByLabel('Repeat passphrase').fill(pass);
    await page.getByRole('button', { name: 'Create private archive' }).click();
    await page.getByLabel('What is on your mind?').fill('These words stay exactly where I put them.');
    await page.getByRole('button', { name: 'Keep it', exact: true }).click();
    await page.getByRole('button', { name: 'Keep this thought' }).click();
    const on = page.getByRole('button', { name: 'Falling letters on', exact: true });
    const off = page.getByRole('button', { name: 'Falling letters off', exact: true });
    await on.click();
    assert.equal(await off.getAttribute('aria-pressed'), 'false');
    await page.locator('.note-open').click();
    assert.equal(await page.locator('.editor-falling-text').count(), 0);
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.locator('.note-editor').waitFor({ state: 'detached' });
    assert.equal(await page.locator('.diary-note').getAttribute('data-piled'), 'false');
    await page.getByRole('button', { name: 'Turn room light off' }).click();
    await page.mouse.move(0, 0);
    assert.equal(await page.locator('.diary-note').getAttribute('data-piled'), 'false');
    assert.ok(await page.locator('.diary-note .pile-letter').evaluateAll(letters => letters.every(el => getComputedStyle(el).transform === 'none')));
    await page.getByText('Saved encrypted on this device', { exact: true }).waitFor();
    await page.reload();
    await page.getByLabel('Passphrase', { exact: true }).fill(pass);
    await page.getByRole('button', { name: 'Unlock archive' }).click();
    await off.waitFor();
    await page.getByRole('link', { name: '← Lobby' }).click();
    await page.getByRole('link', { name: 'Create a new room' }).click();
    await page.getByLabel('Room name').fill('A different mood');
    await page.getByRole('button', { name: 'Hang it up' }).click();
    await on.waitFor();
    await page.getByRole('link', { name: '← Lobby' }).click();
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.screenshot({ path: `/tmp/night-gallery-${width}.png` });
    }
    assert.equal(await page.locator('.night-star').count(), 6);
    assert.equal(await page.locator('.night-moon').count(), 1);
    const imageURL = await page.locator('.night-clouds').evaluate(el => getComputedStyle(el).backgroundImage.match(/url\("?([^"\)]+)/)?.[1]);
    assert.equal((await page.request.get(imageURL)).status(), 200);
    await page.getByRole('link', { name: 'Open My thoughts', exact: true }).click();
    await off.waitFor();
    const downloading = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export encrypted backup' }).click();
    const backup = await downloading;
    const file = '/tmp/room-motion-backup.json';
    await backup.saveAs(file);
    const restored = await browser.newPage({ reducedMotion: 'reduce' });
    await restored.goto(base);
    await restored.locator('input[type=file]').setInputFiles(file);
    await restored.getByLabel('Passphrase', { exact: true }).fill(pass);
    await restored.getByRole('button', { name: 'Restore backup' }).click();
    await restored.getByRole('link', { name: 'Open My thoughts', exact: true }).click();
    await restored.getByRole('button', { name: 'Falling letters off', exact: true }).waitFor();
    await off.click();
    await page.locator('.note-open').click();
    await page.getByRole('button', { name: 'Done', exact: true }).click();
    await page.locator('.editor-falling-text.is-piled').waitFor();
    await page.locator('.note-editor').waitFor({ state: 'detached' });
    assert.equal(await page.locator('.diary-note').getAttribute('data-piled'), 'true');
    await page.screenshot({ path: '/tmp/room-motion-on.png' });
    assert.deepEqual(errors, []);
    console.log('PASS: per-room falling-letter preference; no pile/delay when off; dimming; reload; independent room defaults; backup/restore; re-enable; moon, six stars, cloud asset and mobile gallery.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
