const {chromium}=require('../web/node_modules/playwright');const assert=require('node:assert/strict');
const base=process.env.QA_BASE_URL||'http://127.0.0.1:5173';
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.qaOscillators=0;const create=AudioContext.prototype.createOscillator;AudioContext.prototype.createOscillator=function(){window.qaOscillators++;return create.call(this);};});await page.goto(base);await page.getByLabel('Passphrase',{exact:true}).waitFor();await page.locator('.arrival').waitFor({state:'detached'});
for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('.vault-entry__form').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await page.screenshot({path:`/tmp/vault-polish-${width}.png`});}
await page.getByLabel('Passphrase',{exact:true}).fill('polished archive phrase');await page.getByLabel('Show passphrase',{exact:true}).check();assert.equal(await page.getByLabel('Passphrase',{exact:true}).getAttribute('type'),'text');await page.getByLabel('Show passphrase',{exact:true}).uncheck();await page.getByLabel('Repeat passphrase').fill('different archive phrase');await page.getByRole('button',{name:'Create private archive'}).click();await page.getByRole('alert').waitFor();assert.ok(await page.getByRole('button',{name:'Create private archive'}).evaluate(e=>e.getAnimations().some(a=>a.effect.getTiming().duration===320)));assert.equal(await page.evaluate(()=>window.qaOscillators),0);
await page.getByLabel('Repeat passphrase').fill('polished archive phrase');await page.getByRole('button',{name:'Create private archive'}).click();await page.getByLabel('What is on your mind?').fill('A little space to breathe.');await page.getByRole('button',{name:'Keep it',exact:true}).click();await page.getByRole('button',{name:'Keep this thought'}).click();await page.getByRole('link',{name:'← Lobby'}).click();await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Chimes off',exact:true}).click();await page.waitForTimeout(800);await page.evaluate(()=>window.qaOscillators=0);await page.getByRole('link',{name:'Open My thoughts',exact:true}).hover();assert.equal(await page.evaluate(()=>window.qaOscillators),3);await page.waitForTimeout(800);await page.locator('.room-tag__tag').first().hover();assert.equal(await page.evaluate(()=>window.qaOscillators),3);await page.screenshot({path:'/tmp/lobby-polish.png'});
assert.equal(await page.locator('.ambient-scene svg').count(),0);
const fold=await page.locator('.night-clouds').evaluate(el=>getComputedStyle(el).transform);await page.waitForTimeout(600);assert.notEqual(await page.locator('.night-clouds').evaluate(el=>getComputedStyle(el).transform),fold);
await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert.ok(await page.locator('.ambient-scene').evaluate(el=>el.getAnimations({subtree:true}).every(a=>a.playState==='paused')));await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
await page.mouse.move(100,200);await page.waitForTimeout(750);const first=await page.locator('.ambient-depth').evaluate(e=>getComputedStyle(e).transform);await page.mouse.move(1200,700);await page.waitForTimeout(750);assert.notEqual(await page.locator('.ambient-depth').evaluate(e=>getComputedStyle(e).transform),first);
await page.getByRole('button',{name:'Chimes on',exact:true}).click();await page.waitForTimeout(800);await page.evaluate(()=>window.qaOscillators=0);await page.getByRole('link',{name:'Open My thoughts',exact:true}).hover();assert.equal(await page.evaluate(()=>window.qaOscillators),0);await page.getByRole('link',{name:'Open My thoughts',exact:true}).click();await page.locator('.diary-room').waitFor();await page.getByRole('button',{name:'Hide screen',exact:true}).click();await page.getByRole('button',{name:'Return',exact:true}).click();await page.getByRole('button',{name:'Unlock archive'}).waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/vault-returning.png'});await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.ambient-depth').evaluate(e=>getComputedStyle(e).transform),'none');assert.deepEqual(errors,[]);console.log('PASS: create/returning passphrase layouts at 1440/390/320; show password; field errors; entry click depth; muted by default; room hover chime once per entry; mute; background depth; room navigation; reduced motion; no page errors.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
